#!/bin/sh

# ===================================================================
# nix/home-manager - https://github.com/nix-community/home-manager
# ===================================================================

switch_home()
{
  # download the latest rupurt/nix-home if we don't have it
  if [ ! -e 'install_home_manager' ]; then
    NIX_HOME_ARCHIVE_URL=https://github.com/rupurt/nix-home/archive/refs/heads/main.zip
    echo "fetching nix-home from $NIX_HOME_ARCHIVE_URL"

    curl -sSf -L $NIX_HOME_ARCHIVE_URL -o /tmp/nix-home.zip
    unzip -o /tmp/nix-home.zip -d /tmp
    cd /tmp/nix-home-main
  fi

  HOME_MANAGER_VERSION=$(home-manager --version 2>/dev/null)
  if [ $? -eq 0 ]; then
    echo "home-manager is already installed version=[$HOME_MANAGER_VERSION]"
    home-manager switch -b backup --flake .
  else
    echo "running home-manager switch via nix run"
    nix run home-manager/master -- switch -b backup --flake .
  fi
}

# ensure nix is installed and activated in the current shell
if [ -x "$(command -v nix --version)" ]; then
  switch_home
else
  echo "nix is not installed or activated in the current shell"
fi
